### ISSUE TITLE
Write R function unit test and internal code: daily return

### ISSUE THREAD

**Issue by ciciecho-ds** [UBC-MDS/CryptocurrencyEDAr#15]

**Comment by alexYinanGu0** [comment]
Hi team. We talked about inputting data frame for this function. But I still think that inputting array would be better, because if someone wants to just use this function in our package to do some simple calculation, they do not need to convert the numbers they have to data frame. I changed the example in docstring to take in a column of a data frame so it can be more coherent to other 3 functions in our package.
